setwd("C:/Users/manu/Documents/coursera")
data1<-read.csv("household_power_consumption.txt",sep=";",header=T)
head(data1)
data1$Date<-as.Date(data1$Date,"%d/%m/%Y")

data2<-subset(data1, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
head(data2)
data2$uniDate <- as.POSIXct(paste(Date, Time), format="%Y-%m-%d %H:%M:%S")
attach(data2)
Sub_metering_1<-as.numeric(as.character(Sub_metering_1))
Sub_metering_2<-as.numeric(as.character(Sub_metering_2))
Sub_metering_3<-as.numeric(as.character(Sub_metering_3))
plot(uniDate,Sub_metering_1,type = "l",xlab="",ylab="Energy Sub metering")
points(uniDate,Sub_metering_2,col="red",type="l")
points(uniDate,Sub_metering_3,col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),lwd=c(2,2),col=c("black","red","blue"))
dev.copy(png,file="Plot3.png")
dev.off()
