setwd("C:/Users/manu/Documents/coursera")
data1<-read.csv("household_power_consumption.txt",sep=";",header=T)
head(data1)
data1$Date<-as.Date(data1$Date,"%d/%m/%Y")

data2<-subset(data1, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
head(data2)
attach(data2)
Global_active_power<-as.numeric(as.character(Global_active_power))
Global_reactive_power<-as.numeric(as.character(Global_reactive_power))
data2$uniDate <- as.POSIXct(paste(Date, Time), format="%Y-%m-%d %H:%M:%S")
Sub_metering_1<-as.numeric(as.character(Sub_metering_1))
Sub_metering_2<-as.numeric(as.character(Sub_metering_2))
Sub_metering_3<-as.numeric(as.character(Sub_metering_3))
attach(data2)
par(mfrow=c(2,2))
plot(uniDate,Global_active_power,type = "l",xlab="",ylab="Global Active Power")
plot(uniDate,Voltage,type = "l",xlab="datetime")
plot(uniDate,Sub_metering_1,type = "l",xlab="",ylab="Energy sub metering")
points(uniDate,Sub_metering_2,col="red",type="l")
points(uniDate,Sub_metering_3,col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),bty="n",cex=0.80,col=c("black","red","blue"))
plot(uniDate,Global_reactive_power,type = "l",lwd=0.1,xlab="datetime")
dev.copy(png,file="Plot4.png")
dev.off()
